set_property SRC_FILE_INFO {cfile:D:/HDL_PRAC/project_HA_Beh_GL/project_HA_Beh_GL.srcs/constrs_1/new/PM_HA.xdc rfile:../../../project_HA_Beh_GL.srcs/constrs_1/new/PM_HA.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports S_233_229]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports C_233_229]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports A]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports B]
