set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports q_160_163]
set_property IOSTANDARD LVCMOS33 [get_ports q_bar_160_163]
set_property PACKAGE_PIN U12 [get_ports r]
set_property PACKAGE_PIN U11 [get_ports s]
set_property PACKAGE_PIN V10 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports reset]
set_property PACKAGE_PIN V11 [get_ports q_160_163]
set_property PACKAGE_PIN V12 [get_ports q_bar_160_163]

