set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports SUM]
set_property IOSTANDARD LVCMOS33 [get_ports CARRY]
set_property PACKAGE_PIN V10 [get_ports A]
set_property PACKAGE_PIN U11 [get_ports B]
set_property PACKAGE_PIN V11 [get_ports SUM]
set_property PACKAGE_PIN V12 [get_ports CARRY]
