set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports CARRY_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_Sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALU_OUT[3]}]


set_property PACKAGE_PIN P5 [get_ports {ALU_OUT[3]}]

set_property PACKAGE_PIN T1 [get_ports {A[0]}]
set_property PACKAGE_PIN R3 [get_ports {A[1]}]
set_property PACKAGE_PIN P3 [get_ports {A[2]}]
set_property PACKAGE_PIN P4 [get_ports {A[3]}]
set_property PACKAGE_PIN U4 [get_ports {B[0]}]
set_property PACKAGE_PIN V2 [get_ports {B[1]}]
set_property PACKAGE_PIN T3 [get_ports {B[3]}]
set_property PACKAGE_PIN U2 [get_ports {B[2]}]
set_property PACKAGE_PIN R5 [get_ports {ALU_Sel[0]}]
set_property PACKAGE_PIN V7 [get_ports {ALU_Sel[1]}]
set_property PACKAGE_PIN V6 [get_ports {ALU_Sel[2]}]
set_property PACKAGE_PIN V5 [get_ports {ALU_Sel[3]}]
set_property PACKAGE_PIN P2 [get_ports {ALU_OUT[0]}]
set_property PACKAGE_PIN R2 [get_ports {ALU_OUT[1]}]
set_property PACKAGE_PIN U1 [get_ports {ALU_OUT[2]}]
set_property PACKAGE_PIN R1 [get_ports CARRY_OUT]
